cmd_util/demangle-cxx.o := g++ -Wp,-MD,util/.demangle-cxx.o.d -Wp,-MT,util/demangle-cxx.o -Werror -std=gnu++17 -fno-exceptions -fno-rtti -Wall -Wextra -fno-omit-frame-pointer -I/home/paddymac/llama.cpp/perf-6.9.0/tools/perf/util/include -I/home/paddymac/llama.cpp/perf-6.9.0/tools/perf/arch/x86/include -I/home/paddymac/llama.cpp/perf-6.9.0/tools/include/ -I/home/paddymac/llama.cpp/perf-6.9.0/tools/arch/x86/include/uapi -I/home/paddymac/llama.cpp/perf-6.9.0/tools/include/uapi -I/home/paddymac/llama.cpp/perf-6.9.0/tools/arch/x86/include/ -I/home/paddymac/llama.cpp/perf-6.9.0/tools/arch/x86/ -I/home/paddymac/llama.cpp/perf-6.9.0/tools/perf/util -I/home/paddymac/llama.cpp/perf-6.9.0/tools/perf -DHAVE_CXA_DEMANGLE_SUPPORT -D"BUILD_STR(s)=$(pound)s"   -c -o util/demangle-cxx.o util/demangle-cxx.cpp

source_util/demangle-cxx.o := util/demangle-cxx.cpp

deps_util/demangle-cxx.o := \
  /usr/include/stdc-predef.h \
  util/demangle-cxx.h \
  /usr/include/c++/13/stdlib.h \
  /usr/include/c++/13/cstdlib \
  /usr/include/x86_64-linux-gnu/c++/13/bits/c++config.h \
  /usr/include/x86_64-linux-gnu/c++/13/bits/os_defines.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/timesize.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/include/x86_64-linux-gnu/c++/13/bits/cpu_defines.h \
  /usr/include/c++/13/pstl/pstl_config.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/lib/gcc/x86_64-linux-gnu/13/include/stddef.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/x86_64-linux-gnu/bits/types/locale_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__locale_t.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/time64.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endianness.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h \
  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/c++/13/bits/std_abs.h \
  /usr/include/string.h \
  /usr/include/strings.h \
  /home/paddymac/llama.cpp/perf-6.9.0/tools/include/linux/compiler.h \
  /home/paddymac/llama.cpp/perf-6.9.0/tools/include/linux/compiler_types.h \
  /home/paddymac/llama.cpp/perf-6.9.0/tools/include/linux/compiler-gcc.h \
  /home/paddymac/llama.cpp/perf-6.9.0/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/13/include/stdbool.h \
  /usr/lib/gcc/x86_64-linux-gnu/13/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-least.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/paddymac/llama.cpp/perf-6.9.0/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/paddymac/llama.cpp/perf-6.9.0/tools/include/asm-generic/bitsperlong.h \
  /home/paddymac/llama.cpp/perf-6.9.0/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/c++/13/cxxabi.h \
  /usr/include/x86_64-linux-gnu/c++/13/bits/cxxabi_tweaks.h \
  /usr/include/c++/13/bits/cxxabi_forced.h \
  /usr/include/c++/13/bits/cxxabi_init_exception.h \
  /usr/include/c++/13/typeinfo \
  /usr/include/c++/13/bits/exception.h \
  /usr/include/c++/13/bits/hash_bytes.h \

util/demangle-cxx.o: $(deps_util/demangle-cxx.o)

$(deps_util/demangle-cxx.o):
